test:
  a:
    a:
      a: "a"
    b: "d"
  b: 1
  c:
    a:
      a:
        a: true
    b:
      a: 3.5
    c: false
  e:
    a:
      a:
        a:
          a: 0.5
          d:
            - '我无语了'
            - '为啥要这样对我'